blank_issues_enabled: true
contact_links:
  - name: Question
    url: https://github.com/NotAFlyingGoose
    about: |
      Got a question about Capy?
      Feel free to email NotAFlyingGoose for anything you're curious about
