[package]
name = "fuzz"
version = "0.1.0"

[package.metadata]
cargo-fuzz = true

[workspace]

[[bin]]
name = "parse_lower"
path = "fuzz_targets/parse_lower.rs"

[dependencies]
ast = {path = "../crates/ast"}
hir = {path = "../crates/hir"}
libfuzzer-sys = "0.3"
parser = {path = "../crates/parser"}
