[package]
name = "codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
disable_codegen_checks = []

[dependencies]
interner = { path = "../interner" }
la-arena = "0.2.0"
hir = { path = "../hir" }
hir_ty = { path = "../hir_ty" }
rustc-hash = "1.1"
cranelift = "0.99.1"
cranelift-module = "0.99.1"
cranelift-jit = "0.99.1"
cranelift-native = "0.99.1"
cranelift-object = "0.99.1"
target-lexicon = "0.12.11"
internment = "0.7.1"
uid_gen = { path = "../uid_gen" }
num-traits = "0.2.16"

[dev-dependencies]
ast = { path = "../ast" }
expect-test = "1.1"
interner = { path = "../interner" }
lexer = { path = "../lexer" }
parser = { path = "../parser" }
test-utils = { path = "../test-utils" }
cfg-if = "1.0.0"
path-clean = "1.0.1"
