[package]
name = "codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
interner = {path = "../interner"}
la-arena = "0.2.0"
hir = {path = "../hir"}
hir_ty = {path = "../hir_ty"}
rustc-hash = "1.1"

[dependencies.inkwell]
git = "https://github.com/TheDan64/inkwell"
branch = "master"
features = ["llvm14-0"]

[dev-dependencies]
ast = {path = "../ast"}
expect-test = "1.1"
interner = {path = "../interner"}
lexer = {path = "../lexer"}
parser = {path = "../parser"}
test-utils = {path = "../test-utils"}
