[package]
name = "codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
interner = { path = "../interner" }
la-arena = "0.3"
hir = { path = "../hir" }
hir_ty = { path = "../hir_ty" }
rustc-hash = "1.1"
cranelift = "0.108"
cranelift-module = "0.108"
cranelift-jit = "0.108"
cranelift-native = "0.108"
cranelift-object = "0.108"
target-lexicon = "0.12"
internment = "0.8.3"
uid_gen = { path = "../uid_gen" }
num-traits = "0.2.16"
glob = "0.3.1"

[dev-dependencies]
ast = { path = "../ast" }
expect-test = "1.1"
interner = { path = "../interner" }
lexer = { path = "../lexer" }
parser = { path = "../parser" }
test-utils = { path = "../test-utils" }
cfg-if = "1.0.0"
path-clean = "1.0.1"
